import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import Provider from "./provider";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AppHeader from "./(main)/_components/AppHeader";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "AI-Voice Agent",
  description: "Generated by create next app",
  icons: {
    icon: "./public/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <Provider>
              <AppHeader />
              {children}
              <Toaster />
            </Provider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
